5-2 completed
js-tasks-ru/htmlcss-20230714_grinux pull request #12
Opened 2023-08-02 14:41 UTC by grinux84

2023-08-02 14:42 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-08-04 07:21 UTC, GSemikozov requested changes

2023-08-04 07:21 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +  width: 25%;
сам блок растягивается на всю ширину и высоту вьюпорта, ставится полупрозрачный фон через rgba, а внутри - располагаем элемент блока, собственно окно модалки

2023-08-04 07:21 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +.modal__back {
это лишнее

2023-08-04 10:33 UTC, grinux84 commented on 05-lection3/02-modal/modal.css
> +  width: 25%;
Исправил

2023-08-04 10:33 UTC, grinux84 commented on 05-lection3/02-modal/modal.css
> +.modal__back {
Ок

2023-08-05 20:48 UTC, GSemikozov requested changes

2023-08-05 20:48 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +  position: relative;
fixed

2023-08-05 20:48 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +  position:fixed;
а тут уже либо absolute либо relative

2023-08-06 12:29 UTC, grinux84 commented on 05-lection3/02-modal/modal.css
> +  position: relative;
Исправил

2023-08-06 12:29 UTC, grinux84 commented on 05-lection3/02-modal/modal.css
> +  position:fixed;
Исправил

2023-08-09 08:15 UTC, GSemikozov approved these changes

2023-08-09 08:15 UTC, merged