7-1 checkbox completed
js-tasks-ru/htmlcss-20230714_grinux pull request #21
Opened 2023-08-11 20:33 UTC by grinux84

2023-08-11 20:33 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-08-12 12:06 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-08-12 20:16 UTC, GSemikozov requested changes

2023-08-12 20:16 UTC, GSemikozov commented on 07-lection5/01-checkbox/checkbox.css
> +    .checkbox__control {
это ведь css, не scss, вложенные селекторы использовать в таком виде не можем

2023-08-13 20:20 UTC, GSemikozov approved these changes

2023-08-13 20:20 UTC, merged