7-2 radiobutton completed
js-tasks-ru/htmlcss-20230714_grinux pull request #22
Opened 2023-08-12 13:13 UTC by grinux84

2023-08-12 13:13 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-08-12 20:18 UTC, GSemikozov requested changes

2023-08-12 20:18 UTC, GSemikozov commented on 07-lection5/02-radio/radio.css
> +    .radio__control {
см коммент в МР-е по чекбоксу

2023-08-13 20:20 UTC, GSemikozov approved these changes

2023-08-13 20:20 UTC, jsru commented
К сожалению, PR не может быть замержен, GSemikozov вероятно сможет помочь.

2023-08-13 20:22 UTC, GSemikozov approved these changes

2023-08-13 20:22 UTC, merged