7-4 text input completed
js-tasks-ru/htmlcss-20230714_grinux pull request #24
Opened 2023-08-12 18:10 UTC by grinux84

Вопрос в комменте внутри css

2023-08-12 18:10 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-08-12 20:24 UTC, GSemikozov requested changes

2023-08-12 20:24 UTC, GSemikozov commented on 07-lection5/04-input/index.html
> +          <div class="text-input__title">LABEL</div>
это именно семантический тег label

2023-08-12 20:24 UTC, GSemikozov commented on 07-lection5/04-input/index.html
> +          <div class="text-input__icon"></div>
по структуре - иконки и инпут лучше завернуть в общий враппер, и позиционировать иконку относительно него (причем обе будут в разметке, но скрыты, и показывать надо нужную в зависимости от состояния)

2023-08-12 20:24 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +  .text-input__input {
не используем вложенные селекторы

2023-08-12 20:24 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +    background: url("../../assets/images/icons-sprite.svg#error") center no-repeat; */
иконку из спрайта через фон нет возможности поставить, так работать не будет, лучше иконку добавлять в разметке

2023-08-13 12:16 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-08-13 12:20 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-08-13 12:21 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-08-13 12:31 UTC, grinux84 commented on 07-lection5/04-input/index.html
> +          <div class="text-input__icon"></div>
wrapper там есть, забыл распространить на первый инпут

2023-08-13 12:32 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-08-13 12:33 UTC, grinux84 commented on 07-lection5/04-input/index.html
> +          <div class="text-input__title">LABEL</div>
ok

2023-08-13 12:33 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-08-13 12:33 UTC, grinux84 commented on 07-lection5/04-input/input.css
> +  .text-input__input {
ok

2023-08-13 12:33 UTC, grinux84 commented on 07-lection5/04-input/input.css
> +    background: url("../../assets/images/icons-sprite.svg#error") center no-repeat; */
ok

2023-08-13 15:06 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-08-13 20:24 UTC, GSemikozov requested changes

2023-08-13 20:24 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +  content: "";
content тут лишнее

2023-08-13 21:20 UTC, grinux84 commented on 07-lection5/04-input/input.css
> +  content: "";
исправил

2023-08-14 21:37 UTC, GSemikozov approved these changes

2023-08-14 21:37 UTC, jsru commented
К сожалению, PR не может быть замержен, GSemikozov вероятно сможет помочь.

2023-08-14 21:39 UTC, GSemikozov approved these changes

2023-08-14 21:39 UTC, merged