7-0 tabs completed
js-tasks-ru/htmlcss-20230714_grinux pull request #25
Opened 2023-08-13 17:36 UTC by grinux84

2023-08-13 17:37 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-08-13 20:27 UTC, GSemikozov requested changes

2023-08-13 20:27 UTC, GSemikozov commented on components/tabs/tabs.css
> +.tabs__scroller>div:first-child {
здесь и ниже, как и везде, - привязку к тегам лучше не делать, достаточно использовать классы по БЭМ. И конкретно в данном случае - просто .tabs__menu вместо .tabs__scroller>div:first-child?

2023-08-13 20:27 UTC, GSemikozov commented on components/tabs/tabs.css
> +.tabs__preview {
не описан механизм отображения секций с контентом - если такой-то инпут чекнут, то покажем такую-то секцию (например tabs__content_complex)

2023-08-13 21:19 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-08-13 21:20 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-08-13 21:23 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-08-13 21:31 UTC, grinux84 commented on components/tabs/tabs.css
> +.tabs__scroller>div:first-child {
Исправил

2023-08-13 21:31 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-08-13 21:37 UTC, grinux84 commented on components/tabs/tabs.css
> +.tabs__preview {
Тут есть вопрос. В "подсказке" из ДЗ этот механизм реализован за счет того, что input и контент находятся на одном уровне вложенности. Но в реальности из-за того, что область с табами по цвету отличается от области с превью карточек для них нельзя использовать общий контейнер. Из-за этого нельзя сделать селектор для контента на основе значения инпута т.к. родители разные. Как быть? Можно положить табы с контейнер с карточками и сделать отрицательный маржин вверх, чтобы задрать на хедер с белой подложкой. Но это какие то костыли. Как правильно?

2023-08-14 21:36 UTC, GSemikozov commented on components/tabs/tabs.css
> +.tabs__preview {
проще так:
1. хедер - табы - футер (табы - не часть хедера)
2. табы - по умолчанию растянуты на всю ширину страницы
3. элементы внутри табов можно дополнительно заворачивать как угодно, в том числе в контейнер, а в контент табов поместить блок preview

но в более реальном мире, если это не верста лендинга, то табы конечно же напишем на js

2023-08-15 10:52 UTC, grinux84 commented on components/tabs/tabs.css
> +.tabs__preview {
<div class="tabs__scroller">
            <div class="container">
              <div class="tabs__menu">
                <input type="radio" name="nav-tab" id="#all-tab" checked>
                <label class="tabs__label" for="#all-tab">All components</label>
                <input type="radio" name="nav-tab" id="#complex-tab">
                <label class="tabs__label" for="#complex-tab">Complex</label>
                <input type="radio" name="nav-tab" id="#simple-tab">
                <label class="tabs__label" for="#simple-tab">Simple</label>
              </div>
            </div>
          </div>
          <div class="tabs__content">
            <div class="container">
              <div class="tabs__preview tabs__content_complex">
                <div class="card">

Речь вот про такую структуру, где на уровне tabs__scroller и tabs__content задается разный цвет подложки. А далее два отдельных контейнера. Я не могу сделать селектор из первого контейнера во второй, чтобы скрыть или отобразить tabs__content_complex например.

2023-08-15 11:32 UTC, GSemikozov commented on components/tabs/tabs.css
> +.tabs__preview {
верно, это неправильная структура. В ДЗ предложено размещать инпуты на самом верхнем уровне как непосредственные дочерние элементы блока. А уже ниже - меню с лейблами и контент. И тогда если конкретный инпут checked - показываем соответствующую секцию, а остальное - скрыто.

2023-08-15 11:35 UTC, grinux84 commented on components/tabs/tabs.css
> +.tabs__preview {
Каком образом в таком случае выполнить требование разного цвета подложки таб-меню и таб-контента вне контейнера в той части, которая должна растягиваться, если ширина больше ширины контейнера?

2023-08-18 10:07 UTC, GSemikozov commented on components/tabs/tabs.css
> +.tabs__preview {
'''
Div.tabs
    Input.tabs__input
    Div.tabs__scroller // тянется на всю ширину, фон любого цвета
        Div.container
            Div.tabs__menu
            Label.tabs__menu-item
    Div.tabs__content // тянется на всю ширину, фон любого цвета
'''

2023-08-20 13:11 UTC, grinux84 commented on components/tabs/tabs.css
> +.tabs__preview {
Ok

2023-08-20 13:11 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-08-21 18:59 UTC, GSemikozov requested changes

2023-08-21 18:59 UTC, GSemikozov commented on components/tabs/tabs.css
> +.tabs__scroller {
меню на мобилке должно горизонтально скролиться

2023-08-21 18:59 UTC, GSemikozov commented on components/tabs/tabs.css
> +.tabs input {
.tabs__input?

2023-08-22 15:56 UTC, grinux84 commented on components/tabs/tabs.css
> +.tabs__scroller {
Исправил

2023-08-22 15:57 UTC, grinux84 commented on components/tabs/tabs.css
> +.tabs input {
Ок

2023-08-24 21:18 UTC, GSemikozov requested changes

2023-08-24 21:18 UTC, GSemikozov commented on components/tabs/tabs.css
> +  grid-template-columns: repeat(3, calc(33.3333% - 15px));
можно ведь проще - вместо calc(33.3333% - 15px) указываем 1fr

2023-08-24 21:18 UTC, GSemikozov commented on components/tabs/tabs.css
> +  grid-template-rows: repeat(auto-fill, minmax(350px, auto));
а строки таким образом нет смысла размечать. auto-fill можно использовать на уровне grid-template-columns, но совсем не обязательно

2023-08-25 11:32 UTC, grinux84 commented on components/tabs/tabs.css
> +  grid-template-columns: repeat(3, calc(33.3333% - 15px));
Исправил

2023-08-25 11:33 UTC, grinux84 commented on components/tabs/tabs.css
> +  grid-template-rows: repeat(auto-fill, minmax(350px, auto));
Исправил

2023-08-26 19:35 UTC, GSemikozov approved these changes

2023-08-26 19:35 UTC, merged