Бургер-меню
js-tasks-ru/htmlcss-20230714_grinux pull request #27
Opened 2023-08-24 17:00 UTC by grinux84

2023-08-24 17:01 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-08-24 21:28 UTC, GSemikozov requested changes

2023-08-24 21:28 UTC, GSemikozov commented on 09-lection7/01-burger-menu/burger-menu.css
> +.burger-menu__toggler-state {
в данной задаче переключалку добавлять не надо

2023-08-24 21:28 UTC, GSemikozov commented on 09-lection7/01-burger-menu/burger-menu.css
> +.burger-menu {
блок позиционируется как fixed, растягивается на всю ширину и высоту. А уже элемент блока - имеет белый фон и ограничение по ширине, но - внутри блока

2023-08-25 11:33 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-08-25 12:33 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-08-25 12:34 UTC, grinux84 commented on 09-lection7/01-burger-menu/burger-menu.css
> +.burger-menu__toggler-state {
Хорошо. Ну пусть будет

2023-08-25 12:50 UTC, grinux84 commented on 09-lection7/01-burger-menu/burger-menu.css
> +.burger-menu {
Исправил

2023-08-25 12:51 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-08-25 13:03 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-08-25 13:13 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-08-25 13:18 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-08-25 15:25 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-08-26 20:25 UTC, GSemikozov requested changes

2023-08-26 20:25 UTC, GSemikozov commented on 09-lection7/01-burger-menu/burger-menu.css
> +.burger-menu {
не исправлено. Стили из .burger-menu__background надо перенести сюда, а сам .burger-menu__background удалить

2023-08-26 20:25 UTC, GSemikozov commented on 09-lection7/01-burger-menu/burger-menu.css
> +  position: fixed;
а зедсь уже надо позиционироваться относительно блока, fixed уже не надо, можно absolute

2023-08-26 20:25 UTC, GSemikozov commented on 09-lection7/01-burger-menu/burger-menu.css
> +  left: -23.4375em;
и тут будет 0

2023-08-26 20:25 UTC, GSemikozov commented on 09-lection7/01-burger-menu/burger-menu.css
> +  overflow: scroll;
только по y

2023-08-26 20:25 UTC, GSemikozov commented on 09-lection7/01-burger-menu/burger-menu.css
> +  transition: left 0.3s linear;
это должно работать на уровне блока

2023-08-26 20:28 UTC, grinux84 commented on 09-lection7/01-burger-menu/burger-menu.css
> +.burger-menu {
Как в этом случае моментально убрать-показать бэк и анимировать меню? Если делать анимацию на уровне блока то бэк тоже анимируется.

2023-08-27 07:51 UTC, GSemikozov commented on 09-lection7/01-burger-menu/burger-menu.css
> +.burger-menu {
да, это ок, у нас же фон на уровне всего блока задается. Если хочется по-разному анимировать отображения блока и его элемента - к ним действительно можно применять разные эффекты, и даже можно добавлять delay.

2023-08-27 08:46 UTC, grinux84 commented on 09-lection7/01-burger-menu/burger-menu.css
> +.burger-menu {
Как это сделать? Меню уезжает влево, бэк перестает отображаться или тоже уезжает влево, но без анимации.

2023-08-27 10:16 UTC, GSemikozov commented on 09-lection7/01-burger-menu/burger-menu.css
> +.burger-menu {
1. блок отображается сразу, без анимации (fixed, на весь вьюпорт)
2. анимируем элемент блока привязываясь к изменению его состояния

2023-08-27 11:10 UTC, grinux84 commented on 09-lection7/01-burger-menu/burger-menu.css
> +.burger-menu {
С этого я начал. Но когда я делал display: none, то анимация дочернего блока не работала. Нужно весь блок не скрывать а задвигать?

2023-09-01 21:28 UTC, GSemikozov commented on 09-lection7/01-burger-menu/burger-menu.css
> +.burger-menu {
ага

2023-09-01 21:30 UTC, GSemikozov approved these changes

2023-09-01 21:30 UTC, merged