3-1 completed
js-tasks-ru/htmlcss-20230714_grinux pull request #5
Opened 2023-07-25 15:42 UTC by grinux84

Посмотрите последнюю строчку в button.css. Почему то не срабатывает.

2023-07-25 15:43 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-07-26 05:28 UTC, GSemikozov requested changes

2023-07-26 05:28 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +  padding-left: 53px;
сверху-снизу тоже надо бы

2023-07-26 05:28 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +  font-size: 16px;
не хватает font-family, font-weight, line-height

2023-07-26 05:28 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +  cursor: pointer;
можно сразу на .button

2023-07-26 05:28 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> + /*почему то это не срабатывает */
при pointer-events: none; не будет работать, надо удалить

2023-07-26 05:28 UTC, GSemikozov commented on 03-lection1/01-button/index.html
> +      <button class="button button_primary button_disabled">Primary</button>
вместо класса button_disabled нужно использовать атрибут disabled

2023-07-26 15:06 UTC, grinux84 commented on 03-lection1/01-button/button.css
> +  font-size: 16px;
А если рассматривать кнопку, как универсальный компонент, не нужно ли эти параметры вынести на уровень page или main?

2023-07-26 15:11 UTC, grinux84 commented on 03-lection1/01-button/button.css
> + /*почему то это не срабатывает */
Сделал

2023-07-26 15:11 UTC, grinux84 commented on 03-lection1/01-button/button.css
> +  cursor: pointer;
Сделал

2023-07-26 15:11 UTC, grinux84 commented on 03-lection1/01-button/button.css
> +  padding-left: 53px;
Добавил

2023-07-27 11:51 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +  font-size: 16px;
нет, поскольку здесь речь о внутренней реализации, а не о том, что зависит извне. В нашем макете мы используем 3 разных шрифта

2023-07-27 11:59 UTC, grinux84 commented on 03-lection1/01-button/button.css
> +  font-size: 16px;
Ясно. Добавил

2023-07-27 15:50 UTC, GSemikozov requested changes

2023-07-27 15:50 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +button[disabled] {
.button:disabled

2023-07-27 15:50 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +  cursor: not-allowed;
лишнее

2023-07-27 15:50 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +  opacity: 0.5;
не хватает pointer-events: none

2023-07-27 15:58 UTC, grinux84 commented on 03-lection1/01-button/button.css
> +  opacity: 0.5;
Добавил

2023-07-27 15:58 UTC, grinux84 commented on 03-lection1/01-button/button.css
> +  cursor: not-allowed;
Убрал

2023-07-27 16:00 UTC, grinux84 commented on 03-lection1/01-button/button.css
> +button[disabled] {
исправил

2023-07-29 11:01 UTC, GSemikozov approved these changes

2023-07-29 11:02 UTC, merged