4-1 completed
js-tasks-ru/htmlcss-20230714_grinux pull request #8
Opened 2023-07-31 11:03 UTC by grinux84

2023-07-31 11:07 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-07-31 11:37 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-08-01 15:53 UTC, GSemikozov requested changes

2023-08-01 15:53 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +  min-width: 354px;
лишнее

2023-08-01 15:53 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +  height: 185px;
лишнее

2023-08-01 15:53 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +.histogram__header_title {
просто .histogram__title

2023-08-01 15:53 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +.histogram__header_link {
.histogram__link

2023-08-01 15:53 UTC, GSemikozov commented on 04-lection2/01-histogram/index.html
> +          <div class="histogram__value">
не элемент чарта, подымем наверх

2023-08-01 15:53 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +  margin-top: 6px;
лишнее

2023-08-01 15:53 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +.histogram__data_small {
.histogram__column, оставляем только фон и flex-basis: 9px

2023-08-01 15:53 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +.histogram__data_small {
а высоту - уже в модификаторах - .histogram__column-small и тд

2023-08-01 15:53 UTC, GSemikozov commented on 04-lection2/01-histogram/index.html
> +            <div class="histogram__data_small"></div>
ошибка использования модификатора - модификатор можно использовать ТОЛЬКО с тем ЧТО мы модифицируем (в нашем случае это .histogram__column)

2023-08-01 20:48 UTC, grinux84 commented on 04-lection2/01-histogram/histogram.css
> +  min-width: 354px;
Как соблюсти ширину?

2023-08-01 20:53 UTC, grinux84 commented on 04-lection2/01-histogram/histogram.css
> +  height: 185px;
Убрал

2023-08-01 20:53 UTC, grinux84 commented on 04-lection2/01-histogram/histogram.css
> +.histogram__header_link {
Исправил

2023-08-01 20:53 UTC, grinux84 commented on 04-lection2/01-histogram/index.html
> +          <div class="histogram__value">
Переделал

2023-08-01 20:53 UTC, grinux84 commented on 04-lection2/01-histogram/histogram.css
> +  margin-top: 6px;
Перенес в __value

2023-08-01 20:55 UTC, grinux84 commented on 04-lection2/01-histogram/histogram.css
> +.histogram__data_small {
А почему basis именно 9px? Я задал через min-width: 1px. Остальное исправил

2023-08-01 20:55 UTC, grinux84 commented on 04-lection2/01-histogram/index.html
> +            <div class="histogram__data_small"></div>
Да, переделал

2023-08-01 20:55 UTC, grinux84 commented on 04-lection2/01-histogram/histogram.css
> +.histogram__header_title {
Переделал

2023-08-01 20:56 UTC, grinux84 commented on 04-lection2/01-histogram/histogram.css
> +  min-width: 354px;
Через flex-basis 9px для колонки? Как то кривовато...

2023-08-02 09:55 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +  min-width: 354px;
а почему? в макете базовая ширина колонки 9, но можно использовать flex-grow: 1, только если в чарте будет 1 колонка - то она растянется на всю ширину чарта, и вот это точно будет кривовато. Так что flex-basis 9px ОК

2023-08-02 09:55 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +.histogram__data_small {
можно и так

2023-08-02 11:27 UTC, grinux84 commented on 04-lection2/01-histogram/histogram.css
> +  min-width: 354px;
Ширину исправил. По поводу колонок, посмотрел как будут выглядеть две колонки без растяжки, на мой вкус, лучше уж пусть растягиваются, поэтому оставил flex-grow: 1 и min-width: 1px.

2023-08-04 07:12 UTC, GSemikozov requested changes

2023-08-04 07:12 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +  justify-content: space-between;
при gap justify-content точно не надо)

2023-08-04 09:57 UTC, grinux84 commented on 04-lection2/01-histogram/histogram.css
> +  justify-content: space-between;
Убрал

2023-08-05 20:45 UTC, GSemikozov approved these changes

2023-08-05 20:45 UTC, merged