4-2 completed
js-tasks-ru/htmlcss-20230714_grinux pull request #9
Opened 2023-07-31 14:03 UTC by grinux84

2023-07-31 14:04 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-08-01 15:50 UTC, GSemikozov requested changes

2023-08-01 15:50 UTC, GSemikozov commented on 04-lection2/02-skeleton/index.html
> +      <div style="width:579px;height:192px">
высоту даже здесь точно не надо ограничивать

2023-08-01 15:50 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +  width: 100%;
width + height удалим

2023-08-01 15:50 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +  flex-wrap: wrap;
точно надо чтобы переносились?

2023-08-01 15:50 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +  border: 32px solid var(--grey-2);
просто background-color)

2023-08-01 15:50 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +  flex-wrap: wrap;
не надо

2023-08-01 15:50 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton__bar-set + .skeleton__bar-set {
в общем-то лишние стили. Достаточно flex-grow: 1

2023-08-01 20:01 UTC, grinux84 commented on 04-lection2/02-skeleton/index.html
> +      <div style="width:579px;height:192px">
Как соблюсти пропорции компонента, если не задавать размеры родителя?

2023-08-01 20:02 UTC, grinux84 commented on 04-lection2/02-skeleton/skeleton.css
> +  width: 100%;
Вопрос тот же, как остаться в нужном размере?

2023-08-01 20:03 UTC, grinux84 commented on 04-lection2/02-skeleton/skeleton.css
> +  flex-wrap: wrap;
Да, во flex кладется 3 элемента: круг и два набора прогресс баров, второй из которых переносится на новую строку.

2023-08-01 20:04 UTC, grinux84 commented on 04-lection2/02-skeleton/skeleton.css
> +  border: 32px solid var(--grey-2);
Не понял

2023-08-01 20:05 UTC, grinux84 commented on 04-lection2/02-skeleton/skeleton.css
> +  flex-wrap: wrap;
bar-set это набор из двух прогресс баров, второй должен переноситься вниз.

2023-08-01 20:28 UTC, grinux84 commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton__bar-set + .skeleton__bar-set {
Базовая ширина флекса равна размеру контента. После позиционирования круга, нужно в оставшемся месте верхней строки расположить первый набор из двух баров, чтобы он занял все оставшееся место, а второй набор баров перенести на новую строку, и чтобы он занял всю строку. Для этого используем flex-grow и flex-wrap. Поскольку flex-grow применяется к обоим наборам баров, то если для второго не указать flex-basis 100%, то он не перенесется на новую строку, а будет делить оставшееся после позиционирования круга пространство с первым набором баров 1:1

2023-08-01 20:50 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-08-02 09:56 UTC, GSemikozov commented on 04-lection2/02-skeleton/index.html
> +      <div style="width:579px;height:192px">
высота всегда зависит от контента, а ширина - если компонент блочный - от родителя.

2023-08-02 09:58 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +  width: 100%;
в дизайне когда блоки изображены без контекста, абстрактно - размеры блоков носят обычно иллюстративный характер.

2023-08-02 09:59 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +  border: 32px solid var(--grey-2);
для чего используется бордер? элемент окрасит определенным цветом можно через background-color: var(--grey-2);

2023-08-02 10:01 UTC, GSemikozov requested changes

2023-08-02 10:01 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +  flex-wrap: wrap;
у нас уже есть `flex-direction: column;`, при котором все элементы выстраиваются друг под другом

2023-08-02 10:01 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton__bar-set + .skeleton__bar-set {
можно проще - завернуть второй бар в div и все

2023-08-02 11:46 UTC, grinux84 commented on 04-lection2/02-skeleton/skeleton.css
> +  border: 32px solid var(--grey-2);
Бордер в данном случае используется, чтобы нарисовать круг.

2023-08-02 11:49 UTC, grinux84 commented on 04-lection2/02-skeleton/skeleton.css
> +  flex-wrap: wrap;
Точно

2023-08-02 12:01 UTC, grinux84 commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton__bar-set + .skeleton__bar-set {
Можно пример? Если завернуть второй бар в див, то в любом случае нужно сказать флексу, что у этого дива должна быть ширина 100% от родителя иначе он не перенесется.

2023-08-02 12:05 UTC, grinux84 commented on 04-lection2/02-skeleton/index.html
> +      <div style="width:579px;height:192px">
Исправил. Добавил марджин у второго бара, чтобы соблюсти высоту.

2023-08-04 07:13 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +  border: 32px solid var(--grey-2);
тогда зачем указывается ширина и высота? я к тому что не нужно лишних телодвижений делать - рисуем либо через бордер, либо через ширину/высоту + фон

2023-08-04 07:18 UTC, GSemikozov requested changes

2023-08-04 07:18 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton__bar-set + .skeleton__bar-set {
вот примерчик [https://codepen.io/German-Semykozov/pen/GRweZLq](https://codepen.io/German-Semykozov/pen/GRweZLq)

2023-08-04 10:07 UTC, grinux84 commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton__bar-set + .skeleton__bar-set {
Да, понятно, просто другая разметка.

2023-08-05 20:47 UTC, GSemikozov approved these changes

2023-08-05 20:47 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +  border: 32px solid var(--grey-2);
так и не исправлено. Я не настаиваю, мы здесь учимся, так что поставлю аппрув

2023-08-05 20:47 UTC, merged